apiVersion: batch/v1
kind: CronJob
metadata:
  name: multistep-cronjob-example
  labels:
    app: multistep
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: data
            emptyDir: {}
          initContainers:
            - name: init-step-1
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  du -sh /usr/bin
                  tar czf /data/binarch.tar.gz /usr/bin
                  printf "Pause for effect 🦆" && sleep 3
            - name: init-step-2
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  cd /data
                  tar -tzf binarch.tar.gz | wc -l
                  printf "Pause for effect 🐔" && sleep 3
            - name: init-step-3
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  du -sh /data/*
                  printf "Pause for effect 🐇" && sleep 3
          containers:
          - name: finisher-container
            image: ubuntu
            volumeMounts:
            - name: data
              mountPath: /data
            command: 
              - /bin/bash
              - -c
              - |
                echo "Success! 🪱"
