apiVersion: batch/v1
kind: CronJob 
metadata:
  name: multistep-cronjob-example
  labels:
    app: multistep
spec:
  schedule: "15 * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: data
            emptyDir: {}
          restartPolicy: OnFailure
          initContainers:
            - name: init-step-1
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  du -sh /usr/bin
                  tar czf /data/binarch.tar.gz /usr/bin
                  printf "\nPause for effect 🦆\n"
                  sleep 10
            - name: init-step-2
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  cd /data
                  tar -tzf binarch.tar.gz | wc -l
                  printf "\nPause for effect 🐔\n"
                  sleep 10
            - name: init-step-3
              image: ubuntu
              volumeMounts:
              - name: data
                mountPath: /data
              command: 
                - /bin/bash
                - -c
                - |
                  du -sh /data/*
                  printf "\nPause for effect 🐇\n"
                  sleep 10
          containers:
          - name: finisher-container
            image: ubuntu
            volumeMounts:
            - name: data
              mountPath: /data
            command: 
              - /bin/bash
              - -c
              - |
                echo "Success! 🪱"
